# -*- coding: utf-8 -*-
"""P1_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTjKuMKkh6pgnFjmJNhMIDQL89hIdr_B
"""

# @title 預設標題文字
checkerboard=[
  [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

a = list(map(int, input().split()))
b = list(map(int, input().split()))
e = abs(a[0]-b[0])
f = abs(a[1]-b[1])
if checkerboard[b[0]][b[1]] == 0:
  if a[0]!=b[0] or a[1]!=b[1]:
    if e<=1 and f<=1:
      print("Yes")
    else:
      print("No")
  else:
    print("No")
else:
  print("No")